# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '500pxMVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
     pod 'AlamofireObjectMapper', '~> 5.0'
     pod 'Alamofire', '~> 4.7'
  use_frameworks!

  # Pods for 500pxMVVM

end
