# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VIPER Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic 
    pod 'AlamofireObjectMapper', '~> 5.0'
    pod 'Alamofire', '~> 4.7'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'Kingfisher', '~> 4.0'
  use_frameworks!
	
  # Pods for VIPER Sample

end
